name: ci

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/foxystr/test-python-app:1.0 .
      - run: docker push ghcr.io/foxystr/test-python-app:1.0
      - run: docker run ghcr.io/foxystr/test-python-app:1.0
